pre commit fixing

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,16 @@
+#!/usr/bin/env sh
+. "$(dirname -- "$0")/_/husky.sh"
+
 echo "Checking your typescript code..."
-tsc --noEmit
+npx tsc --noEmit || (
+    echo "There's syntax error in your code, please check again";
+    echo
+    false;
+)
 
 echo "Running unit test..."
-npm test
+npm test || (
+    echo "Your code is not pass the unit test please check again";
+    echo
+    false;
+)
